/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package seahorse.url;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        seahorseApplicaion classUnderTest = new seahorseApplicaion();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
