/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package seahorse.url;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class SeahorseApplicationTest {
    @Test
    void contextLoads() {
    }
}