/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package seahorse.url;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class SeahorseApplication {

    public static void main(String... args) {
        SpringApplication.run(SeahorseApplication.class, args);
    }
}
